<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>PCAM - Usuarios</title><link rel="stylesheet" href="css/sistema.css"></head><body>
<?php require VIEW_PATH . '/layouts/header.php'; ?>
<main class="system-bg"><section class="toolbar-card"><div><h1>Usuarios autorizados</h1><p>Registra la IP para permitir entrada automática sin login.</p></div><a class="btn" href="index.php?controller=contenido&action=index">Volver a archivos</a></section>
<section class="files-card">
<?php if($flash):?><div class="flash ok"><?=htmlspecialchars($flash)?></div><?php endif;?><?php if($error):?><div class="flash error"><?=htmlspecialchars($error)?></div><?php endif;?>
<h2>Agregar usuario</h2>
<form class="user-form" method="post" action="index.php?controller=usuarios&action=guardar">
<input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['csrf'])?>"><input name="nombre" placeholder="Nombre completo" required><input name="username" placeholder="Username" required><input name="password" type="password" placeholder="Contraseña" required><input name="email" type="email" placeholder="Email"><input name="ip" placeholder="IP autorizada, ej. 192.168.1.50"><select name="rol_id"><option value="2">Usuario</option><option value="1">Administrador</option></select><input name="nivel_inicial" placeholder="Nivel inicial, ej. Zona_Acapulco"><label><input type="checkbox" name="activo" checked> Activo</label><button class="btn" type="submit">Guardar usuario</button></form>
<div class="table-wrap"><table><thead><tr><th>Nombre</th><th>Usuario</th><th>IP</th><th>Rol</th><th>Nivel</th><th>Activo</th><th>Editar</th></tr></thead><tbody>
<?php foreach($registros as $r):?><tr><td><?=htmlspecialchars($r['nombre'])?></td><td><?=htmlspecialchars($r['username'])?></td><td><?=htmlspecialchars($r['ip'] ?: '—')?></td><td><?=htmlspecialchars($r['rol_nombre'])?></td><td><?=htmlspecialchars($r['nivel_inicial'] ?: 'Raíz')?></td><td><?=$r['activo']?'Sí':'No'?></td><td>
<details><summary>Editar</summary><form class="edit-user" method="post" action="index.php?controller=usuarios&action=guardar"><input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['csrf'])?>"><input type="hidden" name="id" value="<?=$r['id']?>"><input name="nombre" value="<?=htmlspecialchars($r['nombre'])?>" required><input name="username" value="<?=htmlspecialchars($r['username'])?>" required><input name="password" type="password" placeholder="Nueva contraseña (opcional)"><input name="email" value="<?=htmlspecialchars($r['email'])?>"><input name="ip" value="<?=htmlspecialchars($r['ip'])?>" placeholder="IP"><select name="rol_id"><option value="2" <?=$r['rol_id']==2?'selected':''?>>Usuario</option><option value="1" <?=$r['rol_id']==1?'selected':''?>>Administrador</option></select><input name="nivel_inicial" value="<?=htmlspecialchars($r['nivel_inicial'])?>" placeholder="Nivel"><label><input type="checkbox" name="activo" <?=$r['activo']?'checked':''?>> Activo</label><button type="submit">Actualizar</button></form><form method="post" action="index.php?controller=usuarios&action=eliminar" onsubmit="return confirm('¿Eliminar usuario?')"><input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['csrf'])?>"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="danger" type="submit">Eliminar</button></form></details>
</td></tr><?php endforeach;?></tbody></table></div></section></main></body></html>
